### ISSUE TITLE
Requesting new branch for kubernetes-based locust

### ISSUE THREAD

**Issue by gdomanguera** [att-cloudnative-labs/swarmhub#17]
Hi, we are currently in the process of finalizing this new feature where we implemented a kubernetes-based locust. This will also enable a test to run on multiple grids. Can we request a new branch where we can create a pull request. We don't want to mess things up on the master branch.

**Comment by gdomanguera** [comment]
@kmhagan

**Comment by kmhagan** [comment]
Hi @gdomanguera,

I created a new branch feature/k8s-locust

**Comment by gdomanguera** [comment]
thanks 👍
